In [19]:
import pandas as pd

In [20]:
movies = pd.read_csv("Netflix_Dataset_Movie.csv")
movies.head()

   Movie_ID  Year                          Name
0         1  2003               Dinosaur Planet
1         2  2004    Isle of Man TT 2004 Review
2         3  1997                     Character
3         4  1994  Paula Abdul's Get Up & Dance
4         5  2004      The Rise and Fall of ECW

In [21]:
ratings=pd.read_csv('/content/Netflix_Dataset_Rating.csv')
ratings.head()

   User_ID  Rating  Movie_ID
0   712664       5         3
1  1331154       4         3
2  2632461       3         3
3    44937       5         3
4   656399       4         3

In [22]:
print(ratings.shape)

(15588994, 3)

In [23]:
movie_ratings = pd.merge(movies,ratings)
movie_ratings.head()

   Movie_ID  Year       Name  User_ID  Rating
0         3  1997  Character   712664       5
1         3  1997  Character  1331154       4
2         3  1997  Character  2632461       3
3         3  1997  Character    44937       5
4         3  1997  Character   656399       4

In [24]:
movie_ratings=pd.merge(movies,ratings)
movie_ratings.tail()

          Movie_ID  Year                Name  User_ID  Rating
15588989      4056  2001  Planet of the Apes   927245       3
15588990      4056  2001  Planet of the Apes   113294       3
15588991      4056  2001  Planet of the Apes  2032154       5
15588992      4056  2001  Planet of the Apes  2547754       3
15588993      4056  2001  Planet of the Apes   340106       3

In [25]:
movie_ratings=movie_ratings.pivot_table(index=['User_ID'],columns=['Name'],values='Rating')
movie_ratings.head()

Name,10,10 Things I Hate About You,101 Dalmatians II: Patch's London Adventure,11:14,13 Ghosts,18 Again,1984,2 Fast 2 Furious,200 Cigarettes,2010: The Year We Make Contact,...,Xena: Warrior Princess: Season 3,Xena: Warrior Princess: Series Finale,Y Tu Mama Tambien,Yellow Submarine,Yi Yi,Yojimbo,Young Black Stallion,Youngblood,Yu-Gi-Oh!: The Movie,Zorro
User_ID,,,,,,,,,,,,,,,,,,,,,
6,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,5.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
movies['Name'][movies['Name'].str.contains('Wild')]

139                                       Lost in the Wild
219                Winston Churchill: The Wilderness Years
329                                            Wild Things
841                                     Reap the Wild Wind
1508                         National Lampoon's Van Wilder
                               ...
17374    Ocean Wilds: Realm of the Killer Whales/Sperm ...
17390                                   Wildboyz: Season 1
17482    Crocodile Hunter: Wildest Home Videos / Big Cr...
17614                                  Scarecrow Gone Wild
17765    Where the Wild Things Are and Other Maurice Se...
Name: Name, Length: 76, dtype: object

In [27]:
movies['Name'][movies['Name'].str.contains('Wild ')]

329                                            Wild Things
841                                     Reap the Wild Wind
2357                                       The Wild Angels
2389                                            Wild Style
2453                 Jane Goodall's Wild Chimpanzees: IMAX
2558     Mystery Science Theater 3000: The Wild World o...
2692                            How to Stuff a Wild Bikini
3706                     White Wolves: A Cry in The Wild 2
4029                                   Wild in the Country
4669                                        Wild Wild West
4896                          Nikki: Wild Dog of the North
5449     Wacky Babies & Tender Times: Marty Stouffer's ...
6002                                         Wild at Heart
6026                            The Wild Thornberrys Movie
7780                                  Touching Wild Horses
8367                                            Wild Palms
9361           Nature: Cloud: Wild Stallion of the Rockies
9562                                 Walk on the Wild Side
9846                                         Wild Things 2
9895                        Wild Australia: The Edge: IMAX
10141                                         The Wild One
10396                   Wild Things: Diamonds in the Rough
11118                                         Wild America
11180                                           Wild Cardz
11590                                       The Wild Child
14304                                        Wild Orchid 2
14909                                            Wild Bill
14943                                  Run the Wild Fields
15198                                            Wild Side
15271                                          Wild Orchid
15485          Sesame Street: Elmo's World: Wild Wild West
15639                                           Wild Reeds
15713                                            Wild Zero
15785                                    Wild Strawberries
16970                                 Mr. Toad's Wild Ride
17278                                            Wild Arms
17765    Where the Wild Things Are and Other Maurice Se...
Name: Name, dtype: object

In [28]:
movieName=movie_ratings['Character']
movieName

User_ID
6         NaN
7         NaN
79        NaN
97        NaN
134       NaN
           ..
2649370   NaN
2649378   NaN
2649388   NaN
2649426   NaN
2649429   NaN
Name: Character, Length: 143458, dtype: float64

In [29]:
movieName= movie_ratings['7 Seconds']
movieName

User_ID
6          NaN
7          NaN
79         NaN
97         NaN
134        NaN
          ...
2649370    NaN
2649378    NaN
2649388    NaN
2649426    4.0
2649429    NaN
Name: 7 Seconds, Length: 143458, dtype: float64

In [30]:
similar_movies=movie_ratings.corrwith(movieName)

similar_movies.head(10)

Name
10                                             0.120628
10 Things I Hate About You                     0.214530
101 Dalmatians II: Patch's London Adventure    0.372585
11:14                                          0.241550
13 Ghosts                                      0.300361
18 Again                                       0.389876
1984                                           0.222352
2 Fast 2 Furious                               0.327214
200 Cigarettes                                 0.374822
2010: The Year We Make Contact                 0.212211
dtype: float64

In [32]:
similar_movies=movie_ratings.corrwith(movieName)
similar_movies=similar_movies.dropna()

df=pd.DataFrame(similar_movies)

df.head(10)

                                                    0
Name
10                                           0.120628
10 Things I Hate About You                   0.214530
101 Dalmatians II: Patch's London Adventure  0.372585
11:14                                        0.241550
13 Ghosts                                    0.300361
18 Again                                     0.389876
1984                                         0.222352
2 Fast 2 Furious                             0.327214
200 Cigarettes                               0.374822
2010: The Year We Make Contact               0.212211

In [35]:
similar_movies.sort_values(ascending=False)

Name
7 Seconds                1.000000
Love in the Afternoon    0.568752
The Killing              0.561110
Food of Love             0.554591
Not One Less             0.545240
                           ...
Trekkies                -0.085326
The Mouse That Roared   -0.096025
The Return              -0.108211
The Battle of Algiers   -0.135966
Farinelli               -0.247367
Length: 1214, dtype: float64

In [36]:
similar_movies = pd.DataFrame(similar_movies)

In [37]:
similar_movies.head()

                                                    0
Name
10                                           0.120628
10 Things I Hate About You                   0.214530
101 Dalmatians II: Patch's London Adventure  0.372585
11:14                                        0.241550
13 Ghosts                                    0.300361